---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.1.0
- name: debian-6
  driver_config:
    box: opscode-debian-6.0.7
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-6.0.7_chef-11.2.0.box
- name: freebsd-9
  driver_config:
    box: dyn-freebsd-9.1
    box_url: http://dyn-vm.s3.amazonaws.com/vagrant/dyn-chef-11.4.0-virtualbox-freebsd-9.1.box
- name: ubuntu-13.04
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.4
- name: centos-5.9
suites:
- name: default
  run_list:
  - recipe[omnibus]
  attributes:
    build_user: vagrant
    build_dir: /home/vagrant/omnibus
