---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.10
  driver_config:
    box: canonical-ubuntu-12.10
    box_url: http://cloud-images.ubuntu.com/vagrant/quantal/current/quantal-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
- name: debian-6.0.7
  driver_config:
    box: opscode-debian-6.0.7
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-6.0.7_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
  - recipe[netatalk]
  attributes: {}
- name: build_deb
  run_list:
  - recipe[netatalk]
  attributes: { netatalk: { package_recipe: "build_deb" } }
- name: backport_deb
  run_list:
  - recipe[netatalk]
  attributes: { netatalk: { package_recipe: "backport_deb" } }
