---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
    customize:
      memory: 1024 
suites:
- name: default 
  run_list: 
  - recipe[mediacore::database]
  - recipe[mediacore]
  attributes: {
    "postgresql": {
      "password": {
        "postgres": "testkitchen"
      }
    }
  }
