---
driver_plugin: vagrant
driver_config:

platforms:
- name: chef10-ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true

- name: chef10-ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    require_chef_omnibus: true

- name: chef10-centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true

- name: chef10-centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    require_chef_omnibus: "10.26.0"
- name: chef11-centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    require_chef_omnibus: true

suites:
- name: zenoss_client
  run_list: 
  - recipe[minitest-handler]
  - recipe[zenoss_client_test::client_lwrp]
  attributes:
    zenoss:
      client:
        server: "192.168.1.1" # TODO come up with something better than hard coding a zenoss server for testing
        server_port: 8080
        
