language: ruby
gemfile:
  - Gemfile
rvm:
  - 1.9.2
  - 1.9.3
bundler_args: --without integration
before_script: bundle exec berks install
script: bundle exec strainer test
notifications:
  on_success: change
  on_failure: always
  email:
    - chris@wideeyelabs.com
